name: test
on: [workflow_call]

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_15.3.app"
      - name: Get swift version
        run: swift --version
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
